[project]
name = "2504"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "celery>=5.5.1",
    "flower>=2.0.1",
    "loguru>=0.7.3",
    "redis>=5.2.1",
]
